---
on:
  repository_dispatch:
    types: 
      - help-command

jobs:
  main:
    name: Help Command
    runs-on: ubuntu-latest
    steps:
      - name: Determine variables
        id: vars
        run: |
          maintainers=("xx-maint1-xx" "xx-maint2-xx")
          
          RANDOM=$(date +%s)
          
          maintainer=${maintainers[ $RANDOM % ${#maintainers[@]} ]}
          
          echo "maintainer=$maintainer" >> $GITHUB_OUTPUT

      - uses: actions/github-script@v6
        with:
          script: |
            // adds a comment to the PR (there is the issue API, which works work PRs too)
            github.rest.issues.createComment({
              issue_number: github.event.client_payload.github.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hey there @${{ steps.vars.outputs.maintainer }}, could you please help @${{ github.event.client_payload.github.payload.comment.user.login }} out?'
            })
