name: Update Release Branch

on:
  push:
    branches:
      - release-please--branches--main

jobs:
  terraform-docs:
    name: Update terraform docs in README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Generate TF docs
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0 # v1.0.0
        with:
          find-dir: .
          git-commit-message: "docs: update Terraform docs"
          git-push: true

  terraform-format-push:
    name: Format Terraform Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -write=true -recursive
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4
        with:
          commit_message: "chore: format Terraform code"
